export const WS_EVENTS = {
  TABLE_UPDATED: 'TABLE_UPDATED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_KITCHEN_STATUS_UPDATED: 'ORDER_KITCHEN_STATUS_UPDATED',
  ORDER_BOARD_CLEARED: 'ORDER_BOARD_CLEARED',
  GAMING_SESSION_UPDATED: 'GAMING_SESSION_UPDATED',
  BILL_CREATED: 'BILL_CREATED',
  INVENTORY_LOW_STOCK: 'INVENTORY_LOW_STOCK'
};
